[package]
name = "neutron-cloud"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
neutron-core.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde.workspace = true

[target.'cfg(windows)'.dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_Storage_CloudFilters",
    "Win32_UI_Shell",
    "Win32_System_Registry",
]
